{% set name = "fs.sshfs" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/f0/69/67681541e7c697b3a4f770910874be22c9d7414ec7a1101327751eab649c/fs.sshfs-0.7.0.tar.gz
  sha256: 77c62f9e135890f9b24c834f7b5727e86517a2a8a21d2bfb0a8088c112b1ed74

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - fs >=2.0.7
    - six >=1.10
    - paramiko >=2.0
    - configparser  # [py<35]

test:
  imports:
    - fs.sshfs

about:
  home: https://github.com/althonos/fs.sshfs
  license: LGPL v2.1
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
  summary: 'Pyfilesystem2 over SSH using paramiko'
  description: >
    Once created, the SSHFS filesystem behaves like any other filesystem
    see the Pyfilesystem2 documentation https://pyfilesystem2.readthedocs.io.

extra:
  recipe-maintainers:
    - ReimarBauer
