travis:
  secure:
    BINSTAR_TOKEN: UZe0c7TYdc20ELeLuVoYbOUbW2Kq80IzxWA5FSHbCNyBgxwhv9qNlpC+5eR/J90UeUaCdkqlUA2m26oCd9okty98lV/UItQ8A5IBdnxteW4pTYgKILfgqrekCpqUamu+eZzA8DTlgT8tbDbsgB9+5tRIQGWqtcg2i6qkfn/jkJwRxOzTzCZ4brHQTmLhHLlouT5gjyLU2Qzt7ZByfp23pgtCnXjB7DQIC90stTpLrSJgo1q07Bfr9+qnWpp1109ZYA4bJp2Arm3d1/gCr36RdvNeOwAxhg/8pqxVLO/FaHgl3ba/Xufb5wnToO6tGlZtE5pblntfRnPu9b4+Vb/+9Xqzblll+y3N6V2JSET5OtUmCKjLCVpCZx0BZSxLsUu0w8DZjq7z9hb4Uhh9mH+LRHBvNu7rAwR9iBmhoyJqGS5kaCOgs7zNK3ZWSd1DdojBmjUGVKs3pAnVmzlYcmVW2NNzCSu8bs35PubNOXcxH4A4luGFTZg9eLFe6sJKXATYEbRLhOcTEj73jpeuQFwNJtAEon6Ao6zqy2+3GIjSDg/WHbsjogw+bNDrnPaIa+q2VHB2+xLR+d7hUbk4qMbvWdWJNivpwpkJLmVA9CtnKTTPr5GuGiCu7ah/6z6xd5ddfhaLHRTcfwHcqBgbT/P8B5e27z3+IkQbmykTJMsvguk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
