travis:
  secure:
    BINSTAR_TOKEN: hgHbgo6uWvJgtY8m9Q8mu1PNmWz8A/FA1hTErKCXzCtNfk1JFEpUhTdLB2Ww45EuuFICL1q++9aXY7R61mEBNuD2wqv9hZqOVfBxdX/sHcxBzbY25ctpdQHuzxumwgugwUcqDhiDTUVM22absHOukgjc3wv4nvI/QdQKTtHgz9sgTAlydIkSK4ayYOyXE0G4RT+WLj8yjQKdok6jL8q9+GjHNOt9N5sDvfqsaBtx7LBnE3lVc582aA0xY9/lY8ELuqQqggUKsNweN8eQj3VegFVHvCCzrIa4/tx9hlTuhNOn45jMYkMwlwaiJcPlOmI7CTsb0IiJ3i2ltULc3Zxqw35G5TlFp682VuwsspImR4Dbu2rwZNS/U7G+jmuTc61me59YZoKzj8JrftBSEZ7T7of3kl8sn1vUpJzQLKzLHgyJohixKWn49ia0Icc3Mf9UEDn4p0c06hG1c63qHCJAl6E5KWAj3o/faapYTQ5tYGrlnebT36ZeO824ZnbpRYjNbV7vb5GlmsZ4hEUQ4QpZm78jpZaNfH03Ni68FndCAL3TPv8mVYBHuvIZk7hi96QEMTsO8OD9OL4B8X8Fb3/SXjsdo5JQFK9KCm9/t3RQNH4g6ORbxNeKnQj6e+dTfwBKV/qdQdOJjXLW0g3QmZPL6fCD/ZU593WSANFQQLJ/X/I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
